sudo: required
services: 
    - docker

before_install:
    - docker build -t vermontphil/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run vermontphil/react-test npm test -- --coverage

after_success:
    - docker build -t vermontphil/multi-client ./client
    - docker build -t vermontphil/multi-nginx ./nginx
    - docker build -t vermontphil/multi-server ./server
    - docker build -t vermontphil/multi-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push vermontphil/multi-client
    - docker push vermontphil/multi-nginx
    - docker push vermontphil/multi-server
    - docker push vermontphil/multi-worker